from pathlib import Path
import subprocess
import sys
import os
import pandas as pd
import numpy as np
import shutil


# ============================================================
# P7.6 — OUT-OF-SAMPLE VALIDATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PROCESSED_DIR = PROJECT_ROOT / "Dataset" / "processed"
RESULT_DIR = PROJECT_ROOT / "result"
VALIDATION_DIR = RESULT_DIR / "validation"
TEMP_DIR = VALIDATION_DIR / "temp_oos_data"

ENGINE = PROJECT_ROOT / "Src" / "data" / "backtesting_test.py"

VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
TEMP_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# ASSETS
# ============================================================

ASSETS = [
    "RELIANCE",
    "GACM Technologies",
    "ETERNAL",
    "IRFC",
    "RVNL",
    "RailTel",
    "Torrent Power",
    "NIFTY 50",
    "BANK NIFTY",
    "SENSEX",
]


# ============================================================
# OOS PERIOD
# ============================================================

OOS_START = "2026-01-01"


# ============================================================
# HELPERS
# ============================================================

def normalize_name(text):
    """
    Convert filename/asset name into a comparable format.
    Example:
        'GACM-Technologies_clean.csv'
        'GACM Technologies'
    both become similar normalized strings.
    """
    text = str(text).lower()

    for char in [
        "-", "_", " ", ".", "(", ")", "[", "]"
    ]:
        text = text.replace(char, "")

    return text


def find_processed_file(asset):
    """
    Automatically locate processed CSV for an asset.
    """

    csv_files = list(PROCESSED_DIR.glob("*.csv"))

    asset_norm = normalize_name(asset)

    # Direct normalized matching
    for file in csv_files:

        file_norm = normalize_name(file.stem)

        if asset_norm in file_norm:
            return file

    # Special cases
    aliases = {
        "RELIANCE": ["reliance", "reliancens"],
        "GACM Technologies": ["gacm", "gacmtechnologies"],
        "ETERNAL": ["eternal"],
        "IRFC": ["irfc"],
        "RVNL": ["rvnl"],
        "RailTel": ["railtel"],
        "Torrent Power": ["torrentpower", "torrent"],
        "NIFTY 50": ["nifty50", "nsei"],
        "BANK NIFTY": ["banknifty", "nsebank"],
        "SENSEX": ["sensex", "bsesn"],
    }

    for alias in aliases.get(asset, []):

        alias_norm = normalize_name(alias)

        for file in csv_files:

            file_norm = normalize_name(file.stem)

            if alias_norm in file_norm:
                return file

    return None


def find_result_file(asset, suffix):
    """
    Locate result CSV generated by backtesting engine.
    Handles spaces/underscores/hyphens.
    """

    files = list(RESULT_DIR.glob("*.csv"))

    asset_norm = normalize_name(asset)
    suffix_norm = normalize_name(suffix)

    candidates = []

    for file in files:

        file_norm = normalize_name(file.name)

        if asset_norm in file_norm and suffix_norm in file_norm:
            candidates.append(file)

    if candidates:
        return candidates[0]

    return None


def find_date_column(df):
    """
    Find date column automatically.
    """

    possible = [
        "Date",
        "date",
        "Datetime",
        "datetime",
        "Timestamp",
        "timestamp",
    ]

    for col in possible:

        if col in df.columns:
            return col

    # Fallback: inspect columns
    for col in df.columns:

        try:

            converted = pd.to_datetime(
                df[col],
                errors="coerce"
            )

            if converted.notna().sum() > len(df) * 0.8:
                return col

        except Exception:
            pass

    return None


def find_equity_column(df):
    """
    Find equity column robustly.
    """

    preferred = [
        "Equity",
        "equity",
        "Equity_Final",
        "equity_final",
        "Portfolio_Value",
        "portfolio_value",
        "Value",
        "value",
    ]

    for col in preferred:

        if col in df.columns:
            return col

    # Fallback: numeric columns
    numeric_cols = df.select_dtypes(
        include=np.number
    ).columns.tolist()

    if numeric_cols:
        return numeric_cols[-1]

    return None


def find_pnl_column(df):
    """
    Find PnL column robustly.
    """

    possible = [
        "PnL",
        "P&L",
        "Profit",
        "ProfitLoss",
        "Profit_Loss",
        "PL",
    ]

    for col in possible:

        if col in df.columns:
            return col

    # Case-insensitive fallback
    for col in df.columns:

        col_norm = normalize_name(col)

        if col_norm in [
            "pnl",
            "profit",
            "profitloss",
            "pl",
        ]:
            return col

    return None


def calculate_metrics(asset, oos_end_date):
    """
    Read generated equity/trade files and calculate OOS metrics.
    """

    equity_file = find_result_file(
        asset,
        "equity_curve"
    )

    trade_file = find_result_file(
        asset,
        "trade_history"
    )

    if equity_file is None:

        print(
            f"WARNING: Equity curve not found for {asset}"
        )

        return None

    equity = pd.read_csv(equity_file)

    if equity.empty:

        print(
            f"WARNING: Equity curve empty for {asset}"
        )

        return None

    equity_col = find_equity_column(equity)

    if equity_col is None:

        print(
            f"WARNING: Equity column not found for {asset}"
        )

        print(
            "Available columns:",
            list(equity.columns)
        )

        return None

    equity_values = pd.to_numeric(
        equity[equity_col],
        errors="coerce"
    ).dropna()

    if len(equity_values) < 2:

        print(
            f"WARNING: Not enough equity data for {asset}"
        )

        return None

    initial_equity = float(
        equity_values.iloc[0]
    )

    final_equity = float(
        equity_values.iloc[-1]
    )

    return_pct = (
        (final_equity / initial_equity) - 1
    ) * 100


    # --------------------------------------------------------
    # Maximum Drawdown
    # --------------------------------------------------------

    running_max = equity_values.cummax()

    drawdown = (
        (equity_values - running_max)
        / running_max
    ) * 100

    max_drawdown = float(
        drawdown.min()
    )


    # --------------------------------------------------------
    # Sharpe Ratio
    # --------------------------------------------------------

    returns = equity_values.pct_change().dropna()

    if (
        len(returns) > 1
        and returns.std() != 0
    ):

        sharpe = (
            returns.mean()
            / returns.std()
        ) * np.sqrt(252)

    else:

        sharpe = 0.0


    # --------------------------------------------------------
    # Trade Metrics
    # --------------------------------------------------------

    total_trades = 0
    win_rate = 0.0
    profit_factor = 0.0

    if trade_file is not None:

        trades = pd.read_csv(
            trade_file
        )

        if not trades.empty:

            pnl_col = find_pnl_column(
                trades
            )

            if pnl_col:

                pnl = pd.to_numeric(
                    trades[pnl_col],
                    errors="coerce"
                ).dropna()

                total_trades = len(pnl)

                if len(pnl) > 0:

                    winning = pnl[pnl > 0]
                    losing = pnl[pnl < 0]

                    win_rate = (
                        len(winning)
                        / len(pnl)
                    ) * 100

                    if len(losing) > 0:

                        profit_factor = (
                            winning.sum()
                            / abs(losing.sum())
                        )

                    elif len(winning) > 0:

                        profit_factor = np.inf


    # --------------------------------------------------------
    # Return result
    # --------------------------------------------------------

    return {
        "Asset": asset,
        "OOS_Start": OOS_START,
        "OOS_End": str(oos_end_date),
        "InitialEquity": initial_equity,
        "FinalEquity": final_equity,
        "ReturnPct": return_pct,
        "SharpeRatio": sharpe,
        "MaxDrawdownPct": max_drawdown,
        "WinRatePct": win_rate,
        "ProfitFactor": profit_factor,
        "TotalTrades": total_trades,
    }


# ============================================================
# MAIN
# ============================================================

print("=" * 70)
print("P7.6 — OUT-OF-SAMPLE VALIDATION")
print("=" * 70)

print()
print("Fixed strategy parameters:")
print("EMA              : 20 / 50")
print("RSI Threshold    : 50")
print("Stop Loss        : 5%")
print("Reward/Risk      : 1:2")
print("Risk per trade   : 1%")
print("Commission       : 0.1%")

print()
print(
    f"OOS Start Date   : {OOS_START}"
)

print(
    "OOS End Date     : Latest available dataset"
)

print()


# ============================================================
# RESULTS
# ============================================================

results = []

successful_tests = 0
skipped_tests = 0


# ============================================================
# PROCESS EACH ASSET
# ============================================================

for asset in ASSETS:

    print("-" * 70)
    print(f"Testing: {asset}")

    source_file = find_processed_file(
        asset
    )

    # --------------------------------------------------------
    # Dataset not found
    # --------------------------------------------------------

    if source_file is None:

        print(
            f"WARNING: Dataset not found for {asset}"
        )

        skipped_tests += 1

        continue


    # --------------------------------------------------------
    # Read original dataset
    # --------------------------------------------------------

    try:

        df = pd.read_csv(
            source_file
        )

    except Exception as e:

        print(
            f"ERROR reading dataset: {e}"
        )

        skipped_tests += 1

        continue


    # --------------------------------------------------------
    # Date column
    # --------------------------------------------------------

    date_col = find_date_column(
        df
    )

    if date_col is None:

        print(
            f"WARNING: Date column not found for {asset}"
        )

        skipped_tests += 1

        continue


    df[date_col] = pd.to_datetime(
        df[date_col],
        errors="coerce"
    )

    df = df.dropna(
        subset=[date_col]
    )


    # --------------------------------------------------------
    # OOS DATA
    # --------------------------------------------------------

    oos_df = df[
        df[date_col] >= pd.Timestamp(
            OOS_START
        )
    ].copy()


    # --------------------------------------------------------
    # Not enough OOS data
    # --------------------------------------------------------

    if len(oos_df) < 60:

        print(
            f"WARNING: Only {len(oos_df)} OOS rows "
            f"for {asset}. Skipping."
        )

        skipped_tests += 1

        continue


    oos_start_date = oos_df[
        date_col
    ].min().date()

    oos_end_date = oos_df[
        date_col
    ].max().date()


    print(
        f"OOS rows: {len(oos_df)}"
    )

    print(
        f"Date range: "
        f"{oos_start_date} → {oos_end_date}"
    )


    # --------------------------------------------------------
    # Backup original dataset
    # --------------------------------------------------------

    backup_file = (
        TEMP_DIR / source_file.name
    )

    shutil.copy2(
        source_file,
        backup_file
    )


    try:

        # ----------------------------------------------------
        # Replace with OOS-only dataset
        # ----------------------------------------------------

        oos_df.to_csv(
            source_file,
            index=False
        )


        print(
            "Running existing backtesting engine..."
        )


        # ----------------------------------------------------
        # Force UTF-8 on Windows
        # ----------------------------------------------------

        env = dict(
            os.environ
        )

        env["PYTHONIOENCODING"] = "utf-8"
        env["PYTHONUTF8"] = "1"


        # ----------------------------------------------------
        # Run engine
        # ----------------------------------------------------

        process = subprocess.run(
            [
                sys.executable,
                str(ENGINE)
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env
        )


        # ----------------------------------------------------
        # Engine failed
        # ----------------------------------------------------

        if process.returncode != 0:

            print(
                f"Engine failed for {asset}"
            )

            print(
                process.stderr[-2000:]
            )

            skipped_tests += 1

            continue


        # ----------------------------------------------------
        # Extract results
        # ----------------------------------------------------

        metrics = calculate_metrics(
            asset,
            oos_end_date
        )


        if metrics is not None:

            results.append(
                metrics
            )

            successful_tests += 1


            print(
                f"Return       : "
                f"{metrics['ReturnPct']:.2f}%"
            )

            print(
                f"Sharpe       : "
                f"{metrics['SharpeRatio']:.3f}"
            )

            print(
                f"Max DD       : "
                f"{metrics['MaxDrawdownPct']:.2f}%"
            )

            print(
                f"Win Rate     : "
                f"{metrics['WinRatePct']:.2f}%"
            )

            print(
                f"Profit Factor: "
                f"{metrics['ProfitFactor']:.2f}"
            )

            print(
                f"Trades       : "
                f"{metrics['TotalTrades']}"
            )

            print(
                "Result extracted successfully."
            )

        else:

            print(
                f"WARNING: Could not extract "
                f"results for {asset}"
            )

            skipped_tests += 1


    finally:

        # ----------------------------------------------------
        # ALWAYS RESTORE ORIGINAL DATASET
        # ----------------------------------------------------

        if backup_file.exists():

            shutil.copy2(
                backup_file,
                source_file
            )

            print(
                "Original dataset restored."
            )


# ============================================================
# SAVE RESULTS
# ============================================================

results_df = pd.DataFrame(
    results
)

output_file = (
    VALIDATION_DIR
    / "oos_validation_results.csv"
)


if not results_df.empty:

    results_df.to_csv(
        output_file,
        index=False
    )


    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("P7.6 COMPLETE")
    print("=" * 70)

    print()

    print(
        f"Successful OOS tests: "
        f"{successful_tests} / {len(ASSETS)}"
    )

    print(
        f"Skipped/failed tests : "
        f"{skipped_tests} / {len(ASSETS)}"
    )

    print()

    print(
        "Results saved to:"
    )

    print(
        output_file
    )

    print()

    print(
        results_df.to_string(
            index=False
        )
    )


else:

    print()
    print("=" * 70)
    print("NO OOS RESULTS GENERATED")
    print("=" * 70)


# ============================================================
# FINAL CLEANUP
# ============================================================

for backup_file in TEMP_DIR.glob(
    "*.csv"
):

    backup_file.unlink(
        missing_ok=True
    )


print()
print(
    "All original datasets restored."
)

print("=" * 70)